commit_message: "l10n: Update %language% localization from Crowdin"
pull_request_title: "l10n: Update localizations from Crowdin"
pull_request_labels: ["l10n"]
append_commit_message: false
files:
  - source: /yuki-iptv.pot
    translation: /po/yuki-iptv-%locale_with_underscore%.po
